name: todo_tesk
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  easy_localization: ^3.0.5
  injectable: ^2.3.2
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  sqflite: ^2.3.2
  colorize: ^3.0.0
  hive: ^2.2.3
  flutter_gen: ^5.4.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^4.2.1
  uuid: ^4.3.3
  built_value: ^8.9.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  shared_preferences: ^2.2.2
  animate_do: ^3.3.4
  flutter_screenutil: ^5.9.0
  lottie: ^3.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  go_router_builder: ^2.4.1
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.4.0
  built_value_generator: ^8.9.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_gen:
  output: lib/core/utils/assets/
  assets:
    enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/lottie/
